# Generated by Django 5.2.3 on 2025-10-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('recipe', models.CharField(max_length=2000)),
                ('ingredients', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'работника',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
