# Generated by Django 5.2.3 on 2025-10-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_menu_personal_delete_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
