# Generated by Django 5.2.3 on 2025-10-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_menu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
    ]
