# Generated by Django 5.2.3 on 2025-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0005_menu_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
