# Generated by Django 5.2.3 on 2025-09-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0008_category_menu_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
