# Generated by Django 5.2.3 on 2025-09-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0010_category_menu_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
