# Generated by Django 5.2.3 on 2025-11-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('order_time', models.DateTimeField(verbose_name='Время бронирования')),
                ('people_count', models.PositiveIntegerField(verbose_name='Количество человек')),
            ],
            options={
                'verbose_name': 'Бронирование столика',
                'verbose_name_plural': 'Бронирования столиков',
            },
        ),
    ]
